<?php

namespace auth\user;

interface UserInterface {

    /**
     * Get User's UID : an INT auto-generated by the DB table.
     *
     * @return int
     */
    public function _getUid() : int;

    /**
     * Get User's username
     *
     * @return string
     */
    public function _getUsername() : string;

    /**
     * Get User's email
     *
     * @return string
     */
    public function _getEmail() : string;

    /**
     * Get User's permissions : used for admin check ups and user backend-related operations
     * #TODO : Create Permission system
     *
     * @return array
     */
    public function _getPerms() : array;
}